package model.EntityObjects;

import java.math.BigDecimal;

import model.DMLOperations;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 15 12:44:12 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustPaymentsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CustPaymentsId {
            public Object get(CustPaymentsEOImpl obj) {
                return obj.getCustPaymentsId();
            }

            public void put(CustPaymentsEOImpl obj, Object value) {
                obj.setCustPaymentsId((BigDecimal)value);
            }
        }
        ,
        CustPaymentsDate {
            public Object get(CustPaymentsEOImpl obj) {
                return obj.getCustPaymentsDate();
            }

            public void put(CustPaymentsEOImpl obj, Object value) {
                obj.setCustPaymentsDate((Timestamp)value);
            }
        }
        ,
        CustPaymentsMount {
            public Object get(CustPaymentsEOImpl obj) {
                return obj.getCustPaymentsMount();
            }

            public void put(CustPaymentsEOImpl obj, Object value) {
                obj.setCustPaymentsMount((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(CustPaymentsEOImpl obj) {
                return obj.getCustId();
            }

            public void put(CustPaymentsEOImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        Cust {
            public Object get(CustPaymentsEOImpl obj) {
                return obj.getCust();
            }

            public void put(CustPaymentsEOImpl obj, Object value) {
                obj.setCust((CustEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustPaymentsEOImpl object);

        public abstract void put(CustPaymentsEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTPAYMENTSID = AttributesEnum.CustPaymentsId.index();
    public static final int CUSTPAYMENTSDATE = AttributesEnum.CustPaymentsDate.index();
    public static final int CUSTPAYMENTSMOUNT = AttributesEnum.CustPaymentsMount.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUST = AttributesEnum.Cust.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustPaymentsEOImpl() {
    }

    /**
     * Gets the attribute value for CustPaymentsId, using the alias name CustPaymentsId.
     * @return the value of CustPaymentsId
     */
    public BigDecimal getCustPaymentsId() {
        return (BigDecimal)getAttributeInternal(CUSTPAYMENTSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPaymentsId.
     * @param value value to set the CustPaymentsId
     */
    public void setCustPaymentsId(BigDecimal value) {
        setAttributeInternal(CUSTPAYMENTSID, value);
    }

    /**
     * Gets the attribute value for CustPaymentsDate, using the alias name CustPaymentsDate.
     * @return the value of CustPaymentsDate
     */
    public Timestamp getCustPaymentsDate() {
        return (Timestamp)getAttributeInternal(CUSTPAYMENTSDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPaymentsDate.
     * @param value value to set the CustPaymentsDate
     */
    public void setCustPaymentsDate(Timestamp value) {
        setAttributeInternal(CUSTPAYMENTSDATE, value);
    }

    /**
     * Gets the attribute value for CustPaymentsMount, using the alias name CustPaymentsMount.
     * @return the value of CustPaymentsMount
     */
    public BigDecimal getCustPaymentsMount() {
        return (BigDecimal)getAttributeInternal(CUSTPAYMENTSMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPaymentsMount.
     * @param value value to set the CustPaymentsMount
     */
    public void setCustPaymentsMount(BigDecimal value) {
        setAttributeInternal(CUSTPAYMENTSMOUNT, value);
    }

    /**
     * Gets the attribute value for CustId, using the alias name CustId.
     * @return the value of CustId
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustId.
     * @param value value to set the CustId
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CustEOImpl.
     */
    public CustEOImpl getCust() {
        return (CustEOImpl)getAttributeInternal(CUST);
    }

    /**
     * Sets <code>value</code> as the associated entity CustEOImpl.
     */
    public void setCust(CustEOImpl value) {
        setAttributeInternal(CUST, value);
    }

    /**
     * @param custPaymentsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal custPaymentsId) {
        return new Key(new Object[]{custPaymentsId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EntityObjects.CustPaymentsEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        DMLOperations dml = new DMLOperations();
        int newId = dml.setNewId(getDBTransaction(), "CUST_PAYMENTS_ID", "CUST_PAYMENTS");
        setCustPaymentsId(new BigDecimal(newId));
    }
}
