package model.EntityObjects;

import java.math.BigDecimal;

import model.DMLOperations;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 15 12:40:29 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustInvoicesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CustInvoiceId {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCustInvoiceId();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setCustInvoiceId((BigDecimal)value);
            }
        }
        ,
        CustInvoiceDate {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCustInvoiceDate();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setCustInvoiceDate((Timestamp)value);
            }
        }
        ,
        CustInvoiceMount {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCustInvoiceMount();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setCustInvoiceMount((BigDecimal)value);
            }
        }
        ,
        CustId {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCustId();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        Cust {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCust();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setCust((CustEOImpl)value);
            }
        }
        ,
        CustInvoicesProd {
            public Object get(CustInvoicesEOImpl obj) {
                return obj.getCustInvoicesProd();
            }

            public void put(CustInvoicesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustInvoicesEOImpl object);

        public abstract void put(CustInvoicesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTINVOICEID = AttributesEnum.CustInvoiceId.index();
    public static final int CUSTINVOICEDATE = AttributesEnum.CustInvoiceDate.index();
    public static final int CUSTINVOICEMOUNT = AttributesEnum.CustInvoiceMount.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUST = AttributesEnum.Cust.index();
    public static final int CUSTINVOICESPROD = AttributesEnum.CustInvoicesProd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustInvoicesEOImpl() {
    }

    /**
     * Gets the attribute value for CustInvoiceId, using the alias name CustInvoiceId.
     * @return the value of CustInvoiceId
     */
    public BigDecimal getCustInvoiceId() {
        return (BigDecimal)getAttributeInternal(CUSTINVOICEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustInvoiceId.
     * @param value value to set the CustInvoiceId
     */
    public void setCustInvoiceId(BigDecimal value) {
        setAttributeInternal(CUSTINVOICEID, value);
    }

    /**
     * Gets the attribute value for CustInvoiceDate, using the alias name CustInvoiceDate.
     * @return the value of CustInvoiceDate
     */
    public Timestamp getCustInvoiceDate() {
        return (Timestamp)getAttributeInternal(CUSTINVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustInvoiceDate.
     * @param value value to set the CustInvoiceDate
     */
    public void setCustInvoiceDate(Timestamp value) {
        setAttributeInternal(CUSTINVOICEDATE, value);
    }

    /**
     * Gets the attribute value for CustInvoiceMount, using the alias name CustInvoiceMount.
     * @return the value of CustInvoiceMount
     */
    public BigDecimal getCustInvoiceMount() {
        return (BigDecimal)getAttributeInternal(CUSTINVOICEMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustInvoiceMount.
     * @param value value to set the CustInvoiceMount
     */
    public void setCustInvoiceMount(BigDecimal value) {
        setAttributeInternal(CUSTINVOICEMOUNT, value);
    }

    /**
     * Gets the attribute value for CustId, using the alias name CustId.
     * @return the value of CustId
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustId.
     * @param value value to set the CustId
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CustEOImpl.
     */
    public CustEOImpl getCust() {
        return (CustEOImpl)getAttributeInternal(CUST);
    }

    /**
     * Sets <code>value</code> as the associated entity CustEOImpl.
     */
    public void setCust(CustEOImpl value) {
        setAttributeInternal(CUST, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCustInvoicesProd() {
        return (RowIterator)getAttributeInternal(CUSTINVOICESPROD);
    }

    /**
     * @param custInvoiceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal custInvoiceId) {
        return new Key(new Object[]{custInvoiceId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EntityObjects.CustInvoicesEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        
        DMLOperations dml = new DMLOperations();
        int newId = dml.setNewId(getDBTransaction(), "CUST_INVOICE_ID", "CUST_INVOICES");
        setCustInvoiceId(new BigDecimal(newId));
    }
}
