package model.EntityObjects;

import java.math.BigDecimal;

import model.DMLOperations;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 15 12:45:07 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustPhonesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CustPhonesId {
            public Object get(CustPhonesEOImpl obj) {
                return obj.getCustPhonesId();
            }

            public void put(CustPhonesEOImpl obj, Object value) {
                obj.setCustPhonesId((BigDecimal)value);
            }
        }
        ,
        CustPhones {
            public Object get(CustPhonesEOImpl obj) {
                return obj.getCustPhones();
            }

            public void put(CustPhonesEOImpl obj, Object value) {
                obj.setCustPhones((String)value);
            }
        }
        ,
        CustId {
            public Object get(CustPhonesEOImpl obj) {
                return obj.getCustId();
            }

            public void put(CustPhonesEOImpl obj, Object value) {
                obj.setCustId((BigDecimal)value);
            }
        }
        ,
        Cust {
            public Object get(CustPhonesEOImpl obj) {
                return obj.getCust();
            }

            public void put(CustPhonesEOImpl obj, Object value) {
                obj.setCust((CustEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CustPhonesEOImpl object);

        public abstract void put(CustPhonesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTPHONESID = AttributesEnum.CustPhonesId.index();
    public static final int CUSTPHONES = AttributesEnum.CustPhones.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int CUST = AttributesEnum.Cust.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustPhonesEOImpl() {
    }

    /**
     * Gets the attribute value for CustPhonesId, using the alias name CustPhonesId.
     * @return the value of CustPhonesId
     */
    public BigDecimal getCustPhonesId() {
        return (BigDecimal)getAttributeInternal(CUSTPHONESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPhonesId.
     * @param value value to set the CustPhonesId
     */
    public void setCustPhonesId(BigDecimal value) {
        setAttributeInternal(CUSTPHONESID, value);
    }

    /**
     * Gets the attribute value for CustPhones, using the alias name CustPhones.
     * @return the value of CustPhones
     */
    public String getCustPhones() {
        return (String)getAttributeInternal(CUSTPHONES);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustPhones.
     * @param value value to set the CustPhones
     */
    public void setCustPhones(String value) {
        setAttributeInternal(CUSTPHONES, value);
    }

    /**
     * Gets the attribute value for CustId, using the alias name CustId.
     * @return the value of CustId
     */
    public BigDecimal getCustId() {
        return (BigDecimal)getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustId.
     * @param value value to set the CustId
     */
    public void setCustId(BigDecimal value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CustEOImpl.
     */
    public CustEOImpl getCust() {
        return (CustEOImpl)getAttributeInternal(CUST);
    }

    /**
     * Sets <code>value</code> as the associated entity CustEOImpl.
     */
    public void setCust(CustEOImpl value) {
        setAttributeInternal(CUST, value);
    }

    /**
     * @param custPhonesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal custPhonesId) {
        return new Key(new Object[]{custPhonesId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EntityObjects.CustPhonesEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        DMLOperations dml = new DMLOperations();
        int newId = dml.setNewId(getDBTransaction(), "CUST_PHONES_ID", "CUST_PHONES");
        setCustPhonesId(new BigDecimal(newId));
    }
}
