package model.EntityObjects;

import java.math.BigDecimal;

import model.DMLOperations;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 15 12:46:39 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProdCatEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProdCatId {
            public Object get(ProdCatEOImpl obj) {
                return obj.getProdCatId();
            }

            public void put(ProdCatEOImpl obj, Object value) {
                obj.setProdCatId((BigDecimal)value);
            }
        }
        ,
        ProdCatName {
            public Object get(ProdCatEOImpl obj) {
                return obj.getProdCatName();
            }

            public void put(ProdCatEOImpl obj, Object value) {
                obj.setProdCatName((String)value);
            }
        }
        ,
        Prod {
            public Object get(ProdCatEOImpl obj) {
                return obj.getProd();
            }

            public void put(ProdCatEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ProdCatEOImpl object);

        public abstract void put(ProdCatEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PRODCATID = AttributesEnum.ProdCatId.index();
    public static final int PRODCATNAME = AttributesEnum.ProdCatName.index();
    public static final int PROD = AttributesEnum.Prod.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProdCatEOImpl() {
    }

    /**
     * Gets the attribute value for ProdCatId, using the alias name ProdCatId.
     * @return the value of ProdCatId
     */
    public BigDecimal getProdCatId() {
        return (BigDecimal)getAttributeInternal(PRODCATID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdCatId.
     * @param value value to set the ProdCatId
     */
    public void setProdCatId(BigDecimal value) {
        setAttributeInternal(PRODCATID, value);
    }

    /**
     * Gets the attribute value for ProdCatName, using the alias name ProdCatName.
     * @return the value of ProdCatName
     */
    public String getProdCatName() {
        return (String)getAttributeInternal(PRODCATNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdCatName.
     * @param value value to set the ProdCatName
     */
    public void setProdCatName(String value) {
        setAttributeInternal(PRODCATNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getProd() {
        return (RowIterator)getAttributeInternal(PROD);
    }

    /**
     * @param prodCatId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal prodCatId) {
        return new Key(new Object[]{prodCatId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EntityObjects.ProdCatEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        DMLOperations dml = new DMLOperations();
        int newId = dml.setNewId(getDBTransaction(), "PROD_CAT_ID", "PROD_CAT");
        setProdCatId(new BigDecimal(newId));
    }
}
