package model.EntityObjects;

import java.math.BigDecimal;

import model.DMLOperations;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 15 12:56:32 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SupEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SupId {
            public Object get(SupEOImpl obj) {
                return obj.getSupId();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setSupId((BigDecimal)value);
            }
        }
        ,
        SupName {
            public Object get(SupEOImpl obj) {
                return obj.getSupName();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setSupName((String)value);
            }
        }
        ,
        ContactPesonName {
            public Object get(SupEOImpl obj) {
                return obj.getContactPesonName();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setContactPesonName((String)value);
            }
        }
        ,
        Balance {
            public Object get(SupEOImpl obj) {
                return obj.getBalance();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setBalance((BigDecimal)value);
            }
        }
        ,
        SupInvoices {
            public Object get(SupEOImpl obj) {
                return obj.getSupInvoices();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupMails {
            public Object get(SupEOImpl obj) {
                return obj.getSupMails();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupPayments {
            public Object get(SupEOImpl obj) {
                return obj.getSupPayments();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupPhones {
            public Object get(SupEOImpl obj) {
                return obj.getSupPhones();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupProd {
            public Object get(SupEOImpl obj) {
                return obj.getSupProd();
            }

            public void put(SupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SupEOImpl object);

        public abstract void put(SupEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SUPID = AttributesEnum.SupId.index();
    public static final int SUPNAME = AttributesEnum.SupName.index();
    public static final int CONTACTPESONNAME = AttributesEnum.ContactPesonName.index();
    public static final int BALANCE = AttributesEnum.Balance.index();
    public static final int SUPINVOICES = AttributesEnum.SupInvoices.index();
    public static final int SUPMAILS = AttributesEnum.SupMails.index();
    public static final int SUPPAYMENTS = AttributesEnum.SupPayments.index();
    public static final int SUPPHONES = AttributesEnum.SupPhones.index();
    public static final int SUPPROD = AttributesEnum.SupProd.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SupEOImpl() {
    }

    /**
     * Gets the attribute value for SupId, using the alias name SupId.
     * @return the value of SupId
     */
    public BigDecimal getSupId() {
        return (BigDecimal)getAttributeInternal(SUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupId.
     * @param value value to set the SupId
     */
    public void setSupId(BigDecimal value) {
        setAttributeInternal(SUPID, value);
    }

    /**
     * Gets the attribute value for SupName, using the alias name SupName.
     * @return the value of SupName
     */
    public String getSupName() {
        return (String)getAttributeInternal(SUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupName.
     * @param value value to set the SupName
     */
    public void setSupName(String value) {
        setAttributeInternal(SUPNAME, value);
    }

    /**
     * Gets the attribute value for ContactPesonName, using the alias name ContactPesonName.
     * @return the value of ContactPesonName
     */
    public String getContactPesonName() {
        return (String)getAttributeInternal(CONTACTPESONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPesonName.
     * @param value value to set the ContactPesonName
     */
    public void setContactPesonName(String value) {
        setAttributeInternal(CONTACTPESONNAME, value);
    }

    /**
     * Gets the attribute value for Balance, using the alias name Balance.
     * @return the value of Balance
     */
    public BigDecimal getBalance() {
        return (BigDecimal)getAttributeInternal(BALANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Balance.
     * @param value value to set the Balance
     */
    public void setBalance(BigDecimal value) {
        setAttributeInternal(BALANCE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSupInvoices() {
        return (RowIterator)getAttributeInternal(SUPINVOICES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSupMails() {
        return (RowIterator)getAttributeInternal(SUPMAILS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSupPayments() {
        return (RowIterator)getAttributeInternal(SUPPAYMENTS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSupPhones() {
        return (RowIterator)getAttributeInternal(SUPPHONES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSupProd() {
        return (RowIterator)getAttributeInternal(SUPPROD);
    }

    /**
     * @param supId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal supId) {
        return new Key(new Object[]{supId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EntityObjects.SupEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        
        DMLOperations dml = new DMLOperations();
        int newId = dml.setNewId(getDBTransaction(), "SUP_ID", "SUP");
        setSupId(new BigDecimal(newId));
    }
}
